name: intern_demo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  get: ^4.6.6
  phone_number: ^2.1.0
  mockito: ^5.4.4
  bloc_test: ^9.1.7
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  image_path: "assets/icons/logo.png"
  android: true
  ios: true

flutter_native_splash:
  color: "#448AFF"
  image: assets/icons/icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
